version: '3.9'
services:
  frontend:
    build:
      context: ./learning-app-frontend  # Path to your frontend directory
    ports:
      - "5173:5173"  # Map container port 5173 to host port 5173
    volumes:
      - ${LOCAL_WORKSPACE_FOLDER:-.}/learning-app-frontend:/app # Mount the frontend directory into the container
    depends_on:
      - backend  # Ensure backend service is started before frontend

  backend:
    build:
      context: ./learning-App-backend  # Path to your backend directory
    ports:
      - "8080:8080"  # Map container port 8080 to host port 8080
    volumes:
      - ${LOCAL_WORKSPACE_FOLDER:-.}/learning-App-backend:/app  # Mount the backend directory into the container
    depends_on:
      - database  # Ensure database service is started before backend

  database:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"  # Set your database root password
    ports:
      - "5432:5432"  # Map container port 5432 to host port 5432
    volumes:
      - pg_data:/var/lib/postgresql/data  # Mount a volume for database files

volumes:
  pg_data:  # Define a named volume for database files