name: Frontend CI

on:
  push:
    branches: [ "main", "US-10NotesTesting" ]
    paths:
      - 'learning-app-frontend/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'learning-app-frontend/**'

jobs:
  run-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./learning-app-frontend
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: npm ci
      - run: npm test
